const P=[['水星','#a7a39c',4879,.387,88,1407.6,.034],['金星','#e7c08a',12104,.723,224.7,-5832.5,177.4],['地球','#5baaff',12756,1,365.2,23.9,23.4],['火星','#e18b66',6792,1.524,687,24.6,25.2],['木星','#d5b590',142984,5.204,4331,9.9,3.1],['土星','#ead4a1',120536,9.572,10747,10.7,26.7],['天王星','#8ed7dd',51118,19.16,30589,-17.2,97.8],['海王星','#627de8',49528,30.18,59800,16.1,28.3]].map(([name,color,diameter,au,year,hours,tilt])=>({name,color,diameter,au,year,hours,tilt}));
const $=s=>document.querySelector(s),canvas=$('#space'),ctx=canvas.getContext('2d');let mode='orbit',selected=2,days=0,playing=!matchMedia('(prefers-reduced-motion: reduce)').matches,last=0,w=0,h=0,hits=[];const rates={orbit:[1,7,30,180,730],spin:[.01,.05,.25,1,10]};const titles={orbit:['ORBIT / 公転','太陽のまわりを、旅する。','惑星をタップして、地球とくらべよう。'],spin:['ROTATION / 自転','同じ時間でも、回り方はちがう。','目印の点を追ってみよう。金星の向きにも注目。'],size:['SIZE / 大きさ','地球をものさしに、くらべる。','すべて同じ縮尺。太陽も表示してみよう。'],distance:['DISTANCE / 距離','太陽系のほとんどは、空間だ。','距離は同じ縮尺。内側の惑星は、ぎゅっと集まる。']};
P.forEach((p,i)=>{let b=document.createElement('button');b.innerHTML=`<span class="dot" style="background:${p.color}"></span>${p.name}`;b.onclick=()=>{selected=i;update()};$('#planets').append(b)});
function update(){document.querySelectorAll('#planets button').forEach((b,i)=>{b.classList.toggle('selected',i===selected);b.setAttribute('aria-pressed',i===selected)});let p=P[selected];$('#metricLabel').textContent=p.name+'の'+({orbit:'公転',spin:'自転',size:'直径',distance:'太陽からの平均距離'}[mode]);let val=mode==='orbit'?p.year:mode==='spin'?Math.abs(p.hours)<48?Math.abs(p.hours):Math.abs(p.hours)/24:mode==='size'?p.diameter:p.au;let unit=mode==='orbit'?'日 / 1周':mode==='spin'?Math.abs(p.hours)<48?'時間 / 1回転':'日 / 1回転':mode==='size'?'km':'AU';$('#metric').innerHTML=`${val.toLocaleString('ja-JP',{maximumFractionDigits:2})} <span>${unit}</span>`;$('#compare').textContent=mode==='orbit'?`地球の約${(p.year/365.2).toFixed(2)}倍の時間`:mode==='spin'?`軸の傾き ${p.tilt}° · ${p.hours<0?'逆向きの自転':'順行の自転'}`:mode==='size'?`地球の約${(p.diameter/12756).toFixed(2)}倍`: '1 AU = 地球と太陽の平均距離（約1億4960万km）';$('#play').textContent=playing?'❚❚':'▶';$('#play').setAttribute('aria-label',playing?'一時停止':'再生');$('#speedOut').textContent=(mode==='spin'?rates.spin:rates.orbit)[$('#speed').value]+(mode==='spin'?'日 / 秒':'日 / 秒');}
function setMode(m){mode=m;days=0;document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.mode===m));let t=titles[m];$('#eyebrow').textContent=t[0];$('#title').textContent=t[1];$('#hint').textContent=t[2];$('#scaleControls').hidden=m!=='size';$('.transport').hidden=m==='size'||m==='distance';$('#scrubArea').hidden=m==='size'||m==='distance';$('#scrub').max=m==='spin'?500:3652;$('#year').textContent=m==='spin'?'地球が1回転 ＋':'地球が1周 ＋';$('#badge').textContent={orbit:'北極側から見た模式図 · 大きさと距離は強調',spin:'上：北側からの回転方向　下：軸の傾き',size:'直径を同じ縮尺で表示 · 環は直径に含まない',distance:'平均距離を同じ縮尺で表示 · 惑星の大きさは強調'}[m];$('#note').textContent=m==='spin'?'自転周期は恒星基準。軸の図は模式図。模様は識別用です。':'軌道は円に簡略化。位置は観測日時の再現ではありません。';update();}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));$('#play').onclick=()=>{playing=!playing;update()};$('#reset').onclick=()=>{days=0;update()};$('#speed').oninput=update;$('#scrub').oninput=e=>{days=+e.target.value;playing=false;update()};$('#year').onclick=()=>{days+=mode==='spin'?23.9/24:365.2;playing=false;update()};$('#full').onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen();
function resize(){const b=canvas.getBoundingClientRect();w=b.width;h=b.height;canvas.width=w*devicePixelRatio;canvas.height=h*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0)}new ResizeObserver(resize).observe(canvas);
function text(s,x,y,color='#a7b4ca',size=12,align='center'){ctx.fillStyle=color;ctx.font=`${size}px "Yu Gothic UI",sans-serif`;ctx.textAlign=align;ctx.fillText(s,x,y)}
function sphere(x,y,r,color,i,phase=0){if(i===5){ctx.strokeStyle='#b9a58b88';ctx.lineWidth=Math.max(2,r*.23);ctx.beginPath();ctx.ellipse(x,y,r*1.75,r*.42,-.3,0,Math.PI*2);ctx.stroke()}let g=ctx.createRadialGradient(x-r*.35,y-r*.4,0,x,y,r);g.addColorStop(0,color);g.addColorStop(.65,color);g.addColorStop(1,'#172031');ctx.fillStyle=g;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();ctx.save();ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.clip();if(i===2){ctx.fillStyle='#85c4a7';for(let a=0;a<3;a++){ctx.beginPath();ctx.ellipse(x+Math.sin(phase+a*2)*r*.7,y+(a-1)*r*.4,r*.24,r*.18,a,0,7);ctx.fill()}}if(i===4||i===5){ctx.strokeStyle='#876b5c66';ctx.lineWidth=Math.max(1,r*.1);for(let k=-2;k<=2;k++){ctx.beginPath();ctx.moveTo(x-r,y+k*r*.27);ctx.lineTo(x+r,y+k*r*.27);ctx.stroke()}}ctx.restore();}
function halo(x,y,r){let g=ctx.createRadialGradient(x,y,r*.3,x,y,r*2.8);g.addColorStop(0,'#ffbd56');g.addColorStop(.35,'#ffb64188');g.addColorStop(1,'#ffaf2200');ctx.fillStyle=g;ctx.beginPath();ctx.arc(x,y,r*2.8,0,7);ctx.fill();sphere(x,y,r,'#ffd274',-1);}
function ringSelect(x,y,r){ctx.strokeStyle='#b7f3dc';ctx.lineWidth=1.5;ctx.beginPath();ctx.arc(x,y,r+5,0,7);ctx.stroke()}
function draw(){ctx.clearRect(0,0,w,h);hits=[];for(let i=0;i<95;i++){ctx.fillStyle=i%5?'#62799544':'#cbdfff66';ctx.fillRect((i*173.73)%w,(i*83.17)%h,1,1)}if(mode==='orbit'){let cx=w*.5,cy=h*.54,max=Math.min(w*.43,h*.41);halo(cx,cy,16);P.forEach((p,i)=>{let r=max*(.19+i*.115);ctx.strokeStyle=i===selected?'#a0d5c566':'#37475c66';ctx.beginPath();ctx.arc(cx,cy,r,0,7);ctx.stroke();let a=i*.68+days/p.year*Math.PI*2;let x=cx+Math.cos(a)*r,y=cy-Math.sin(a)*r,pr=[4,6,7,5,13,11,9,9][i];sphere(x,y,pr,p.color,i);if(i===selected)ringSelect(x,y,pr);text(p.name,x,y+pr+18,p.color,11);hits.push({x,y,r:Math.max(18,pr),i});});text('↶ 公転',cx,cy+38,'#e3c587',11)}
if(mode==='spin'){let cols=w<650?4:8,rows=8/cols,cw=w/cols,r=Math.min(cw*.29,h/(rows*4.8));P.forEach((p,i)=>{let col=i%cols,row=Math.floor(i/cols),x=cw*(col+.5),y=55+row*(h-60)/rows+r;let angle=days*24/p.hours*Math.PI*2;sphere(x,y,r,p.color,i,angle);let mx=x+Math.cos(angle)*r*.72,my=y-Math.sin(angle)*r*.72;ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(mx,my,4,0,7);ctx.fill();if(i===selected)ringSelect(x,y,r);text(p.hours<0?'↻':'↶',x,y-r-12,'#a7efd6',18);text(p.name,x,y+r+22,p.color,12);let ay=y+r+50,tilt=p.tilt*Math.PI/180;ctx.strokeStyle='#b1c0d7';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x-Math.sin(tilt)*16,ay+Math.cos(tilt)*16);ctx.lineTo(x+Math.sin(tilt)*16,ay-Math.cos(tilt)*16);ctx.stroke();ctx.fillStyle='#b7f3dc';ctx.beginPath();ctx.arc(x+Math.sin(tilt)*16,ay-Math.cos(tilt)*16,3,0,7);ctx.fill();text(p.tilt+'°',x,ay+33,'#7f91aa',10);hits.push({x,y,r:r+10,i})})}
if(mode==='size'){let sun=$('#sunCheck').checked,diameters=sun?[1392700,...P.map(p=>p.diameter)]:P.map(p=>p.diameter),gap=w/(sun?25:32),sum=diameters.reduce((a,b)=>a+b,0),scale=Math.min((w-gap*(diameters.length+1))/sum,(h-110)/Math.max(...diameters));let x=gap;diameters.forEach((d,j)=>{let i=sun?j-1:j,r=d*scale/2,cx=x+r,cy=h*.52;if(i<0){halo(cx,cy,r);text('太陽',cx,cy+r+25,'#ffd274')}else{sphere(cx,cy,r,P[i].color,i);if(i===selected)ringSelect(cx,cy,r);let labelY=h-28-(i%2)*22;ctx.strokeStyle='#41516c';ctx.beginPath();ctx.moveTo(cx,cy+r+7);ctx.lineTo(cx,labelY-14);ctx.stroke();text(P[i].name,cx,labelY,P[i].color,11);hits.push({x:cx,y:cy,r:Math.max(12,r),i})}x+=r*2+gap});text(sun?'太陽の直径 ≈ 地球109個分':'地球の直径 = 1',w-22,60,'#b7f3dc',12,'right')}
if(mode==='distance'){let left=40,right=w-40,y=h*.45,scale=(right-left)/30.18;halo(left,y,12);ctx.strokeStyle='#647589';ctx.beginPath();ctx.moveTo(left,y);ctx.lineTo(right,y);ctx.stroke();P.forEach((p,i)=>{let x=left+p.au*scale,pr=i<4?4:9;sphere(x,y,pr,p.color,i);if(i===selected)ringSelect(x,y,pr);let ly=h*.66+(i<4?i*23:0),lx=i<4?left+24+i*(w<650?44:62):x;ctx.strokeStyle=p.color+'77';ctx.beginPath();ctx.moveTo(x,y+pr+6);ctx.lineTo(lx,ly-14);ctx.stroke();text(p.name,lx,ly,p.color,11);if(i>=4)text(p.au+' AU',lx,ly+19,'#8194b1',10);hits.push({x,y,r:14,i})});for(let n=0;n<=30;n+=5){let x=left+n*scale;text(n+' AU',x,y-35,'#7e8da5',10)}text('太陽',left,y+35,'#ffd274',11)}
$('#clock').textContent=days<10?days.toFixed(2)+'日':Math.floor(days).toLocaleString()+'日';$('#scrub').value=Math.min(days,+$('#scrub').max);}
canvas.onclick=e=>{let b=canvas.getBoundingClientRect(),x=e.clientX-b.left,y=e.clientY-b.top;let hit=hits.filter(p=>Math.hypot(x-p.x,y-p.y)<p.r).sort((a,b)=>Math.hypot(x-a.x,y-a.y)-Math.hypot(x-b.x,y-b.y))[0];if(hit){selected=hit.i;update()}};
function frame(now){let dt=last?Math.min((now-last)/1000,.08):0;last=now;if(playing&&(mode==='orbit'||mode==='spin'))days+=dt*(mode==='spin'?rates.spin:rates.orbit)[$('#speed').value];draw();requestAnimationFrame(frame)}update();requestAnimationFrame(frame);
