// iPad classroom flow: predict, observe, explain. No student data is sent.
let orbitView='all',freeMode=false,taskState={};
const tasks={
 orbit:{question:'地球が1周する間に、いちばん多く回るのは？',choices:['水星','地球','木星'],answer:0,hint:'「地球が1周 ＋」を押して、1周の時間をくらべよう。',reason:'水星は約88日で1周。地球の1年で、約4.2周します。'},
 spin:{question:'同じ時間で、いちばん速く自転するのは？',choices:['地球','木星','金星'],answer:1,hint:'再生して目印を追おう。惑星を選ぶと1回転の時間が出ます。',reason:'木星は約9.9時間で1回転。地球より短い時間で回ります。'},
 size:{question:'木星の直径は、地球の何倍くらい？',choices:['約3倍','約11倍','約100倍'],answer:1,hint:'木星と地球を順にタップして、大きさと比率を確かめよう。',reason:'木星の直径は地球の約11.2倍。大きい球ほど速く自転することもあります。'},
 distance:{question:'地球と太陽の距離を1とすると、海王星までは？',choices:['約3','約10','約30'],answer:2,hint:'海王星を選ぼう。1 AU は地球と太陽の平均距離です。',reason:'海王星は約30 AU。内側の4惑星は太陽の近くに集まっています。'}
};
function renderTask(){let t=tasks[mode],s=taskState[mode]||{step:1,prediction:null};taskState[mode]=s;$('#activity').hidden=freeMode;$('#activity').classList.toggle('observing',s.step!==1);$('#explore').textContent=freeMode?'ミッションに戻る':'自由に観察';$('#taskStep').textContent=s.step===1?'1 予想':s.step===2?'2 観察':'3 発見';$('#question').textContent=t.question;$('#answers').replaceChildren();t.choices.forEach((label,i)=>{let b=document.createElement('button');b.textContent=label;b.classList.toggle('chosen',s.prediction===i);b.setAttribute('aria-pressed',s.prediction===i);b.onclick=()=>{if(s.step!==1)return;s.prediction=i;s.step=2;playing=false;days=0;if(mode==='orbit')orbitView='inner';update();renderTask()};b.disabled=s.step!==1;$('#answers').append(b)});$('#check').hidden=s.step!==2;$('#taskMessage').textContent=s.step===1?'まず予想をタップ。あとで動かして確かめよう。':s.step===2?t.hint:(s.prediction===t.answer?'予想と一致！ ':'予想と比べてみよう。 ')+t.reason;}
$('#check').onclick=()=>{taskState[mode].step=3;playing=false;update();renderTask()};$('#restartTask').onclick=()=>{taskState[mode]={step:1,prediction:null};days=0;playing=false;update();renderTask()};$('#explore').onclick=()=>{freeMode=!freeMode;renderTask()};
const ipadTitles={orbit:'太陽のまわりを回る',spin:'軸のまわりを回る',size:'直径を同じ縮尺でくらべる',distance:'太陽からの距離をくらべる'};
setMode=function(m){mode=m;days=0;playing=false;$('#speed').value=2;document.querySelectorAll('nav button').forEach(b=>{b.classList.toggle('active',b.dataset.mode===m);b.setAttribute('aria-pressed',b.dataset.mode===m)});$('#viewTitle').textContent=ipadTitles[m];$('#orbitControls').hidden=m!=='orbit';$('#scaleControls').hidden=m!=='size';$('.transport').hidden=m==='size'||m==='distance';$('#scrubArea').hidden=m==='size'||m==='distance';$('#year').textContent=m==='spin'?'地球が1回転 ＋':'地球が1周 ＋';$('#selectedCycle').textContent=m==='spin'?'選んだ惑星が1回転 ＋':'選んだ惑星が1周 ＋';$('#note').textContent=m==='spin'?'自転は恒星基準。地球の1回転は約23.9時間（昼夜の1日は約24時間）。模様は模式図。':m==='orbit'?'平均距離の比率を使用。軌道は円に簡略化。惑星の位置は例。':'大きさと距離は別々の縮尺で比較しています。';update();renderTask()};
const baseUpdate=update;
update=function(){baseUpdate();$('#play').textContent=playing?'❚❚ 停止':'▶ 再生';$('#play').setAttribute('aria-label',playing?'停止':'再生');let range=mode==='spin'?Math.max(2,Math.abs(P[selected].hours)/24*1.05):Math.max(365.2*2,P[selected].year*1.05);range=Math.max(range,days*1.05);$('#scrub').max=range;$('#rangeLabel').textContent='0〜'+(mode==='spin'?range.toFixed(1)+'日':(range/365.2).toFixed(1)+'年');$('#badge').textContent=mode==='orbit'?(orbitView==='inner'?'内側4惑星の拡大図':'太陽系全体')+' · 北側から · 距離比は実際、惑星は拡大':mode==='spin'?'軸と一緒に自転を観察 · 球の大きさはそろえて表示':mode==='size'?'直径の比率は実際 · 間隔は比較用': '平均距離の比率は実際 · 惑星は拡大';$('#stageTip').textContent=mode==='orbit'&&orbitView==='all'?'内側が集まる様子 →「内側を拡大」で観察':mode==='spin'?'白い点は表面の目印。裏側に回ると見えなくなります。':'';document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('on',b.dataset.view===orbitView));};
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{orbitView=b.dataset.view;update()});
document.querySelectorAll('#planets button').forEach((b,i)=>b.onclick=()=>{selected=i;if(mode==='orbit'&&i>3)orbitView='all';update()});
$('#selectedCycle').onclick=()=>{days+=mode==='spin'?Math.abs(P[selected].hours)/24:P[selected].year;playing=false;update()};
$('#full').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else if(document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen();else{$('#full').textContent='横向きで大きく表示';setTimeout(()=>$('#full').textContent='⛶ 全画面',2500)}}catch{$('#full').textContent='横向きで使おう'}};
function line(x1,y1,x2,y2,color='#405470',width=1){ctx.strokeStyle=color;ctx.lineWidth=width;ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke()}
function drawOrbit(){let count=orbitView==='inner'?4:8,maxAU=orbitView==='inner'?1.85:32,cx=w*.5,cy=h*.55,outer=Math.min(w*.43,h*.36),scale=outer/maxAU;halo(cx,cy,12);if(orbitView==='inner'){ctx.strokeStyle='#8395a455';ctx.setLineDash([3,5]);ctx.beginPath();ctx.arc(cx,cy,outer*.97,0,7);ctx.stroke();ctx.setLineDash([]);text('小惑星帯の方向',cx+outer*.6,cy-outer*.75,'#869bb6',11)}else{let rad=2.7*scale;ctx.strokeStyle='#b7c5dd55';ctx.lineWidth=3;ctx.beginPath();ctx.arc(cx,cy,rad,0,7);ctx.stroke();ctx.lineWidth=1;}
 P.slice(0,count).forEach((p,i)=>{let r=p.au*scale;ctx.strokeStyle=i===selected?'#b7f3dc77':'#617ca155';ctx.beginPath();ctx.arc(cx,cy,r,0,7);ctx.stroke();let a=.25+i*.68+days/p.year*Math.PI*2,x=cx+Math.cos(a)*r,y=cy-Math.sin(a)*r,pr=orbitView==='inner'?[7,9,10,8][i]:i<4?2.5:[12,10,8,8][i-4];sphere(x,y,pr,p.color,i);if(i===selected)ringSelect(x,y,pr);if(orbitView==='inner'){let lx=w<650?w*(i%2===0?.25:.75):w*.83,ly=w<650?h-75+Math.floor(i/2)*30:75+i*50;if(w>=650)line(x+pr,y,lx-50,ly-5,p.color+'44');text(p.name+' '+(days/p.year).toFixed(1)+'周',lx,ly,p.color,w<500?12:15);}else if(i>=4)text(p.name,x,y+pr+21,p.color,w<500?12:15);hits.push({x,y,r:Math.max(22,pr+8),i});});text('太陽',cx,cy+35,'#ffcf78',13);if(orbitView==='all'){text('内側4惑星',cx-70,cy-40,'#c0d1e7',13);line(cx-40,cy-30,cx-8,cy-7)}text('↶ 公転',w-70,h-25,'#b7f3dc',13);}
function drawSpin(){let cols=w<650?4:8,rows=8/cols,cw=w/cols,rowH=(h-78)/rows;P.forEach((p,i)=>{let x=cw*(i%cols+.5),top=45+Math.floor(i/cols)*rowH,r=Math.min(cw*.29,rowH*.23,58),y=top+r+24,theta=days*24/Math.abs(p.hours)*Math.PI*2,tilt=p.tilt*Math.PI/180;ctx.save();ctx.translate(x,y);ctx.rotate(-tilt);sphere(0,0,r,p.color,i===2?-1:i,0);ctx.save();ctx.beginPath();ctx.arc(0,0,r,0,7);ctx.clip();ctx.strokeStyle='#e0f0ff66';ctx.lineWidth=1;for(let n=0;n<4;n++){let a=theta+n*Math.PI/2;if(Math.cos(a)>0){ctx.beginPath();ctx.ellipse(0,0,Math.max(.5,Math.abs(Math.sin(a))*r),r,0,-Math.PI/2,Math.PI/2,Math.sin(a)<0);ctx.stroke()}}if(i===2){ctx.fillStyle='#83c7a3';for(let k=0;k<3;k++){let a=theta+k*2;if(Math.cos(a)>0){ctx.beginPath();ctx.ellipse(Math.sin(a)*r*.85,(k-1)*r*.35,Math.max(1,Math.cos(a)*r*.2),r*.14,0,0,7);ctx.fill()}}}line(-r,0,r,0,'#d5e6fa55');if(Math.cos(theta)>0){ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(Math.sin(theta)*r,0,4,0,7);ctx.fill()}ctx.restore();line(0,-r-13,0,r+13,'#c3e8dc',2);ctx.fillStyle='#b7f3dc';ctx.beginPath();ctx.arc(0,-r-13,3,0,7);ctx.fill();ctx.restore();if(i===selected)ringSelect(x,y,r+2);text(p.name,x,y+r+34,p.color,w<500?12:15);text(p.tilt+'°',x,y+r+55,'#a7b9d1',12);text(p.hours<0?'逆向き ↻':'↶',x,top-2,'#b7f3dc',12);hits.push({x,y,r:r+16,i})})}
function drawSize(){let includeSun=$('#sunCheck').checked,ds=includeSun?[1392700,...P.map(p=>p.diameter)]:P.map(p=>p.diameter),gap=w/(includeSun?28:34),factor=Math.min((w-gap*(ds.length+1))/ds.reduce((a,b)=>a+b,0),(h-145)/Math.max(...ds)),x=gap,cy=h*.45;ds.forEach((d,j)=>{let i=includeSun?j-1:j,r=d*factor/2,cx=x+r;if(i<0){halo(cx,cy,r);text('太陽',cx,cy+r+23,'#ffd274',14)}else{sphere(cx,cy,r,P[i].color,i);if(i===selected)ringSelect(cx,cy,r);let labelY=h-65-(i%2)*25;line(cx,cy+r+8,cx,labelY-17,'#5c7796');text(P[i].name,cx,labelY,P[i].color,w<500?10:14);hits.push({x:cx,y:cy,r:Math.max(22,r),i})}x+=2*r+gap});if(includeSun)text('太陽の直径 ≈ 地球109個分',w-18,57,'#b7f3dc',w<500?11:14,'right');}
function drawDistance(){let left=38,right=w-40,y=h*.4,scale=(right-left)/30.18;halo(left,y,12);line(left,y,right,y,'#91a3be');for(let n=0;n<=30;n+=5)text(n+' AU',left+n*scale,y-30,'#a7bdd7',w<500?10:13);P.forEach((p,i)=>{let x=left+p.au*scale,pr=i<4?3:8; sphere(x,y,pr,p.color,i);if(i===selected)ringSelect(x,y,pr);let ly=h*.64+(i<4?i*23:0),lx=i<4?left+16+i*(w<500?27:52):x;line(x,y+pr+5,lx,ly-16,p.color+'77');text(p.name,lx,ly,p.color,w<500?11:14);if(i>=4)text(p.au.toFixed(1)+' AU',lx,ly+22,'#a0b4d0',w<500?10:12);hits.push({x,y,r:22,i})});text('太陽',left,y+35,'#ffd274',13);}
draw=function(){ctx.clearRect(0,0,w,h);hits=[];for(let i=0;i<75;i++){ctx.fillStyle='#9fc5ff44';ctx.fillRect((i*173.73)%w,(i*83.17)%h,1,1)}if(mode==='orbit')drawOrbit();else if(mode==='spin')drawSpin();else if(mode==='size')drawSize();else drawDistance();$('#clock').textContent=days<10?days.toFixed(2)+'日':mode==='orbit'&&days>730?(days/365.2).toFixed(1)+'年':Math.floor(days).toLocaleString()+'日';$('#scrub').value=Math.min(days,+$('#scrub').max);};
// Lower spin rates prevent misleading stroboscopic motion at the fastest setting.
rates.spin=[.01,.05,.25,.5,1];rates.orbit=[1,7,30,365.2,3652];
playing=false;setMode('orbit');
